#release configuration
#Thu Sep 03 15:57:02 CEST 2026
completedPhase=end-release
exec.activateProfiles=deploy-to-scijava
exec.additionalArguments=-Dgpg.skip\=true 
exec.pomFileName=pom.xml
exec.snapshotReleasePluginAllowed=false
pinExternals=false
preparationGoals=clean verify
project.dev.org.mastodon\:mastodon=1.0.0-beta-37-SNAPSHOT
project.rel.org.mastodon\:mastodon=1.0.0-beta-36
project.scm.org.mastodon\:mastodon.connection=scm\:git\:https\://github.com/mastodon-sc/mastodon
project.scm.org.mastodon\:mastodon.developerConnection=scm\:git\:git@github.com\:mastodon-sc/mastodon
project.scm.org.mastodon\:mastodon.tag=HEAD
project.scm.org.mastodon\:mastodon.url=https\://github.com/mastodon-sc/mastodon
projectVersionPolicyConfig=<projectVersionPolicyConfig>${projectVersionPolicyConfig}</projectVersionPolicyConfig>\n
projectVersionPolicyId=default
pushChanges=false
releaseStrategyId=default
remoteTagging=true
scm.branchCommitComment=@{prefix} prepare branch @{releaseLabel}
scm.commentPrefix=[maven-release-plugin] 
scm.developmentCommitComment=@{prefix} prepare for next development iteration
scm.releaseCommitComment=@{prefix} prepare release @{releaseLabel}
scm.rollbackCommitComment=@{prefix} rollback the release of @{releaseLabel}
scm.tag=mastodon-1.0.0-beta-36
scm.tagNameFormat=@{project.artifactId}-@{project.version}
scm.url=scm\:git\:https\://github.com/mastodon-sc/mastodon
